import os
import json
import re
import shutil

# Safely import PyMuPDF for signature image extraction and template heuristic reading
try:
    import fitz  # PyMuPDF
    HAS_FITZ = True
except ImportError:
    HAS_FITZ = False

from wolfgang_client import WolfgangClient
from auditor import ai_deep_audit_batch
from compliance_matrix import ALL_MATRICES

def normalize_str(s):
    if not s: return ""
    return re.sub(r'[^a-z0-9]', '', str(s).lower())

def get_qualities(doc_name, compliance_map):
    """Smart fetcher that matches the dynamic categories generated by the auditor.py"""
    norm_doc = normalize_str(doc_name)
    if norm_doc in compliance_map:
        return compliance_map[norm_doc]
            
    for key, items in compliance_map.items():
        if key in norm_doc or norm_doc in key:
            return items
            
    return []

def detect_template_heuristics(pdf_path, company_name):
    """Aggressively checks for blank templates using regex and placeholder density."""
    if not HAS_FITZ or not pdf_path.lower().endswith(".pdf"):
        return False
    
    try:
        doc = fitz.open(pdf_path)
        text = ""
        for i in range(min(10, len(doc))):
            text += doc[i].get_text().lower() + " "
        doc.close()
        
        comp_normalized = company_name.lower().split()[0]
        has_company = comp_normalized in text
        
        placeholders = len(re.findall(r'\[.*?\]|\<.*?\>', text))
        template_phrases = ["company name", "customer name", "partner name", "insert here", "yyyymmdd"]
        has_template_phrase = any(p in text for p in template_phrases)

        if has_template_phrase: return True
        if not has_company and placeholders >= 3: return True
        if placeholders >= 6: return True
            
        return False
    except Exception:
        return False

def extract_signature_image(pdf_path, doc_name):
    if not HAS_FITZ or not pdf_path.lower().endswith(".pdf"): 
        return None
        
    try:
        doc = fitz.open(pdf_path)
        best_page = -1
        max_score = 0
        
        sig_keywords = {
            "electronically signed by:": 20, 
            "docusign": 10, "digitally signed": 10, 
            "signature:": 5, "approved by": 5, "sign here": 5,
            "signed by": 4, "date:": 1, "title:": 1
        }
        
        for i in range(len(doc)):
            text = doc[i].get_text().lower()
            score = 0
            for kw, weight in sig_keywords.items():
                if kw in text:
                    score += weight * text.count(kw)
                    
            if score > max_score:
                max_score = score
                best_page = i
                
        if best_page == -1:
            for i in range(max(0, len(doc) - 3), len(doc)):
                images = doc[i].get_images()
                for img in images:
                    if img[2] > 50 and img[3] > 20: 
                        best_page = i
                        break
                if best_page != -1:
                    break
        
        if best_page == -1:
            best_page = len(doc) - 1 
            
        page = doc[best_page]
        
        pix = page.get_pixmap(matrix=fitz.Matrix(2.0, 2.0))
        os.makedirs("temp_signatures", exist_ok=True)
        
        clean_name = re.sub(r'[^a-zA-Z0-9]', '_', doc_name)
        out_path = f"temp_signatures/{clean_name}_sig.png"
        pix.save(out_path)
        
        doc.close()
        return out_path
    except Exception as e:
        print(f"Error extracting signature for {doc_name}: {e}")
        return None

def run_pipeline(company, project_category, project_type, log_callback=None, progress_callback=None, forced_phase=None, folder_name="Unknown"):
    base = f"downloads/{company}"
    
    COMPLIANCE_MATRIX = ALL_MATRICES.get(project_category, ALL_MATRICES["MINT"])
    PHASE_ORDER = list(COMPLIANCE_MATRIX.keys())

    if log_callback: log_callback("[SYSTEM] Booting Wolfgang Client & authenticating session...")
    if progress_callback: progress_callback(0, 1, "Initializing Wolfgang AI Connection...")
    
    wolfgang = WolfgangClient()

    try:
        all_files = []
        for root, _, files in os.walk(base):
            for f in files:
                all_files.append(os.path.join(root, f))

        all_files = list(set(all_files))
        if log_callback: log_callback(f"[SYSTEM] Found {len(all_files)} total files. Beginning deep audit...")

        ai_results = ai_deep_audit_batch(
            "Full Project", all_files, wolfgang,
            project_category=project_category,
            log_callback=log_callback, progress_callback=progress_callback
        )

        if log_callback: log_callback("[SYSTEM] Deep audit complete. Initializing Backend Verification Checklist...")
        if progress_callback: progress_callback(1, 1, "Reconciling Checklist & Generating Report...")

        from collections import defaultdict
        compliance_map = defaultdict(list)
        
        if isinstance(ai_results, list):
            for item in ai_results:
                c_type = item.get("compliance_type")
                if c_type: 
                    compliance_map[normalize_str(c_type)].append(item)

        final = {}
        
        working_phases = PHASE_ORDER
        if forced_phase and forced_phase in PHASE_ORDER:
            allowed_index = PHASE_ORDER.index(forced_phase)
            working_phases = PHASE_ORDER[:allowed_index + 1]
            if log_callback: log_callback(f"[SYSTEM] Forcing audit scope to stop at phase: {forced_phase}")

        checklist_logs = []
        missing_critical_docs = []

        for phase in working_phases:
            phase_docs_dict = COMPLIANCE_MATRIX.get(phase, {})
            phase_results = []

            for doc, allowed_types in phase_docs_dict.items():
                
                if project_category == "MINT" and "MINT SS" in folder_name.upper() and normalize_str("IRD") in normalize_str(doc):
                    if log_callback: log_callback(f"[SYSTEM] MINT SS Project detected. Bypassing IRD requirement.")
                    continue
                    
                if project_type not in allowed_types:
                    continue
                    
                is_optional = "optional" in doc.lower() or "conditional" in doc.lower()
                is_bypassed = is_optional 

                qualities = get_qualities(doc, compliance_map)

                if not qualities:
                    if is_optional:
                        phase_results.append({
                            "document": doc, "quality": {}, "score": 0, "pass": True,
                            "wrong_folder": False, "actual_folder": "N/A", "expected_phase": phase,
                            "comment": "N/A: Optional/Conditional Requirement.",
                            "signature_image_path": None,
                            "is_bypassed": True
                        })
                        checklist_logs.append(f"[CHECKLIST] {doc} ➖ Bypassed (Optional)")
                    else:
                        phase_results.append({
                            "document": doc, "quality": {}, "score": 0, "pass": False,
                            "wrong_folder": False, "actual_folder": "N/A", "expected_phase": phase,
                            "comment": "Missing: No document submitted for this requirement.",
                            "signature_image_path": None,
                            "is_bypassed": False
                        })
                        missing_critical_docs.append(doc)
                        checklist_logs.append(f"[CHECKLIST] {doc} ❌ Missing")
                    continue

                best_score, best_quality = -1, None
                for q in qualities:
                    score = 0
                    if q.get("appears_filled"): score += 30
                    if q.get("contains_project_content"): score += 30
                    if not q.get("appears_template_only"): score += 20
                    if q.get("document_type_correct"): score += 20
                    if score > best_score:
                        best_score, best_quality = score, q

                if best_quality is None: best_quality, best_score = {}, 0

                file_path = best_quality.get("file_path", "")
                wrong_folder = False
                actual_folder = "N/A"
                
                is_template = False
                if file_path:
                    is_template = detect_template_heuristics(file_path, company)
                    if is_template:
                        best_score = 0
                        best_quality["appears_template_only"] = True

                if file_path:
                    actual_folder = os.path.basename(os.path.dirname(file_path))
                    if actual_folder.lower() == company.lower():
                        actual_folder = "Root Directory"
                        
                    phase_keyword = phase.split()[0].lower() 
                    if phase_keyword not in file_path.lower():
                        wrong_folder = True

                comment = best_quality.get("short_summary", "")
                signature_image_path = None
                
                sig_keywords = ["designdoc", "sow", "statementofwork", "servicesow", "changeorder", "configurationspec", "configspec", "systemreadiness", "transitiontosupport", "projectcompletion", "hld", "ird"]
                requires_signature = any(kw in normalize_str(doc) for kw in sig_keywords)
                
                if is_template:
                    comment = "⚠️ Blank Template Detected. " + comment
                else:
                    if wrong_folder:
                        best_score = max(0, best_score - 10)
                        comment = f"⚠️ Misplaced Penalty (-10%). Found in: {actual_folder}. " + comment
                        
                    if requires_signature:
                        if file_path and file_path.lower().endswith(".pdf"):
                            signature_image_path = extract_signature_image(file_path, doc)
                            if signature_image_path:
                                comment += " [System: Signature proof extracted successfully]."
                            else:
                                best_score = max(0, best_score - 10)
                                comment = "⚠️ Missing Signature Penalty (-10%). " + comment

                if is_optional:
                    comment = "[Optional/Conditional Document] " + comment
                elif not comment:
                    comment = "Complete and adherent." if best_score >= 70 else "Incomplete or template-based."

                if best_score >= 70:
                    checklist_logs.append(f"[CHECKLIST] {doc} ✅ Passed ({best_score}%)")
                else:
                    checklist_logs.append(f"[CHECKLIST] {doc} ⚠️ Failed ({best_score}%)")

                phase_results.append({
                    "document": doc, "quality": best_quality, "score": max(0, best_score),
                    "pass": best_score >= 70, "wrong_folder": wrong_folder,
                    "actual_folder": actual_folder, "expected_phase": phase, "comment": comment,
                    "signature_image_path": signature_image_path,
                    "is_bypassed": is_bypassed
                })

            valid_docs_for_scoring = [d["score"] for d in phase_results if not d.get("is_bypassed", False)]
            avg_score = round(sum(valid_docs_for_scoring) / len(valid_docs_for_scoring), 2) if valid_docs_for_scoring else 100
            
            final[phase] = {"documents": phase_results, "score": avg_score}

        if log_callback:
            log_callback("--- INTERNAL VERIFICATION CHECKLIST ---")
            for clog in checklist_logs:
                log_callback(clog)
            if missing_critical_docs:
                log_callback(f"[CHECKLIST WARNING] {len(missing_critical_docs)} critical documents completely missing.")
            log_callback("---------------------------------------")

        if forced_phase and forced_phase in PHASE_ORDER:
            detected_phase = forced_phase
        else:
            detected_phase = working_phases[0]
            for phase in working_phases:
                has_real_docs = any(d["score"] >= 70 and not d.get("is_bypassed", False) for d in final[phase]["documents"])
                if has_real_docs: 
                    detected_phase = phase

        detected_index = PHASE_ORDER.index(detected_phase)
        active_phases = PHASE_ORDER[:detected_index + 1]
        
        valid_phase_scores = [final[p]["score"] for p in active_phases if p in final]
        overall_score = round(sum(valid_phase_scores) / len(valid_phase_scores), 2) if valid_phase_scores else 0

        risk = "🟢 Low Risk" if overall_score >= 85 else "🟡 Moderate Risk" if overall_score >= 70 else "🟠 High Risk" if overall_score >= 50 else "🔴 Critical Risk"
        
        executive_summary = f"Project assessed at {detected_phase} phase with {overall_score}% adherence. Classified as {risk}."

        return {
            "overall_score": overall_score, "detected_phase": detected_phase,
            "risk_level": risk, "executive_summary": executive_summary, "phases": final,
            "project_category": project_category
        }

    finally:
        wolfgang.close()